# Copyright (c) Facebook, Inc. and its affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

sensor:
  # By default:
  # - Sensor (camera) is placed towards x-axis
  # - Sensor origin is the same as .stl/.obj origin
  
  camera:
    - cam0:
      position: [0, 0, 0] # Camera position
      orientation: [90, 0, -90] # Euler angles, "xyz", in degrees; e.g. [0, 0, 0]: towards negative z-axis; [90, 0, -90]: towards x-axis
      yfov: 22 # Vertical field of view in degrees
      znear: 0.001 # Distance to the near clipping plane, in meters

  gel:
    origin: [0.049, 0, 0.0] # Center coordinate of the gel, in meters
    width: 0.024 # Width of the gel, y-axis, in meters
    height: 0.024 # Height of the gel, z-axis, in meters
    curvature: False  # Model the gel as curve? True/False
    curvatureMax: 0.005  # Deformation of the gel due to convexity
    countW: 100 # Number of samples for horizontal direction; higher the finer details

  light_sources:
    light0:
      position: [-0.866, 0.5, 0.344]
      color: [26, 45, 255]
      kd: 0.6
      ks: 0  # red, upper right
    light1:
      position: [0, -1, 0.344]
      color: [5, 224, 22]
      kd: 0.6
      ks: 0  # green, bottom
    light2:
      position: [0.866, 0.5, 0.344]
      color: [255, 199, 7]
      kd: 0.6
      ks: 0  # blue, upper left

  with_background: True
  background_img: "conf/thusight_nomarker.png"
  ka: 1
  px2m_ratio: 5.9259259259e-5
  elastomer_thickness: 0.01
  max_depth: 0.049  # 相机成像平面到硅胶表面的距离
  enable_depth_texture: False
  texture_sigma: 0.000002
  enable_shadow: False

  noise: # Gaussian noise calibrated on output [0, 255]
    color:
      mean: 0 
      std: 4

  force:
    enable: True # flag for enable force feedback. When enabled, the larger normal force is, the closer object is adjusted to the sensor.
    range_force: [0, 20] # dynamic range of forces used to simulate the elastomer deformation
    max_deformation: 0.002 # max pose depth adjustment, in meters

